apiVersion: v1
kind: Service
metadata:
 name: phpmyadmin
 annotations:
  metallb.universe.tf/allow-shared-ip: shared
spec:
 selector:
  app: phpmyadmin
 type: LoadBalancer
 ports:
 - port: 5000
   name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: phpmyadmin
spec:
 replicas: 1
 selector:
  matchLabels:
   app: phpmyadmin
 template:
  metadata:
   labels:
    app: phpmyadmin
  spec:
   containers:
   - name: phpmyadmin
     image: image-phpmyadmin
     imagePullPolicy: Never
     livenessProbe:
       httpGet:
         path: /
         port: 5000
         scheme: HTTP
       initialDelaySecond: 5
       periodSeconds: 15
       timeoutSeconds: 5
     readinessProbe:
       httpGet:
         path: /
         port: 5000
         scheme: HTTP
       initialDelaySeconds: 5
       timeoutSeconds: 1